name: Build README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7-23/2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Adjust permissions as needed
    steps:
      # Checkout project source code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate updated README file
        run: npm start
        env:
          GH_ACCESS_TOKEN: ${{ github.token }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH_NAME: 'main'
